### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by SJAtreya-TCIN** [nvidia-cosmos/cosmos-transfer1#189]
I have been trying to get the examples (diffusion/inference/transfer.py) working on AWS instances but with no luck. I have tried upto 256GB (8*32GB) A10 GPU on p3dn.24xlarge AWS cluster, but still throws OOME. Controlnet seems to load fine, consumes ~32GB on all 8. But after that, guardrail starts, and within moments, it leads to OOME. This is with the multi-GPU edge inference example provided in the repo.

I am not sure if I need to go upto 192GB. Is there a documentation for hardware requirements? Isaac-sim and other projects provides the hardware type / instance type requirements, would be great if cosmos-transfer also provides the hardware requirements.

Command running:
PYTHONPATH=$(pwd) torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 cosmos_transfer1/diffusion/inference/transfer.py     --checkpoint_dir $CHECKPOINT_DIR     --video_save_folder outputs/example1_single_control_edge     --controlnet_specs assets/inference_cosmos_transfer1_single_control_edge.json     --offload_text_encoder_model     --offload_guardrail_models     --num_gpus 8 --num_steps 20

Output:
[08-25 08:59:33|INFO|cosmos_transfer1/diffusion/model/model_ctrl.py:728:build_model] Start creating base model
[08-25 08:59:35|INFO|cosmos_transfer1/diffusion/model/model_ctrl.py:730:build_model] Done creating base model
[08-25 08:59:35|INFO|cosmos_transfer1/diffusion/model/model_ctrl.py:732:build_model] Start creating ctrlnet model
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:05<00:00, 31.36s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:06<00:00, 31.53s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:02<00:00, 30.60s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:01<00:00, 30.45s/it]

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:04<00:00, 31.09s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:03<00:00, 30.86s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:01<00:00, 30.42s/it]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/cosmos-transfer1/cosmos_transfer1/diffusion/inference/transfer.py", line 411, in <module>
[rank0]:     demo(args, control_inputs)
[rank0]:   File "/home/ubuntu/cosmos-transfer1/cosmos_transfer1/diffusion/inference/transfer.py", line 351, in demo
[rank0]:     batch_outputs = pipeline.generate(
[rank0]:                     ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/cosmos_transfer1/diffusion/inference/world_generation_pipeline.py", line 707, in generate
[rank0]:     is_safe = self._run_guardrail_on_prompt_with_offload(single_prompt)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/cosmos_transfer1/utils/base_world_generation_pipeline.py", line 242, in _run_guardrail_on_prompt_with_offload
[rank0]:     self._load_text_guardrail()
[rank0]:   File "/home/ubuntu/cosmos-transfer1/cosmos_transfer1/utils/base_world_generation_pipeline.py", line 132, in _load_text_guardrail
[rank0]:     self.text_guardrail = guardrail_presets.create_text_guardrail_runner(checkpoint_dir=self.checkpoint_dir)
[rank0]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/cosmos_transfer1/auxiliary/guardrail/common/presets.py", line 32, in create_text_guardrail_runner
[rank0]:     return GuardrailRunner(safety_models=[Blocklist(checkpoint_dir), LlamaGuard3(checkpoint_dir)])
[rank0]:                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/cosmos_transfer1/auxiliary/guardrail/llamaGuard3/llamaGuard3.py", line 46, in __init__
[rank0]:     self.model.to(self.device, dtype=self.dtype).eval()
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/.env/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4346, in to
[rank0]:     return super().to(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/.env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1355, in to
[rank0]:     return self._apply(convert)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/.env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 915, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/home/ubuntu/cosmos-transfer1/.env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 915, in _apply
[rank0]:     module._apply(fn)
[rank0]:   File "/home/ubuntu/cosmos-transfer1/.env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 915, in _apply
[rank0]:     module._apply(fn)
[rank0]:   [Previous line repeated 2 more times]
[rank0]:   File "/home/ubuntu/cosmos-transfer1/.env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 942, in _apply
[rank0]:     param_applied = fn(param)
[rank0]:                     ^^^^^^^^^
[rank0]:   File "/home/ubuntu/cosmos-transfer1/.env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1341, in convert
[rank0]:     return t.to(
[rank0]:            ^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacity of 31.73 GiB of which 86.50 MiB is free. Process 2091 has 580.00 MiB memory in use. Process 2090 has 580.00 MiB memory in use. Process 2094 has 580.00 MiB memory in use. Process 2088 has 580.00 MiB memory in use. Process 2092 has 580.00 MiB memory in use. Including non-PyTorch memory, this process has 27.68 GiB memory in use. Process 2089 has 580.00 MiB memory in use. Process 2093 has 580.00 MiB memory in use. Of the allocated memory 27.18 GiB is allocated by PyTorch, and 121.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by SJAtreya-TCIN** [comment]
Thanks for your response @amolfasale . I will try that. But I guess I understand the nuance behind this software now. It works with 1 H100 GPU instead of 8*32 A10 GPUs.  

Apologies for the the question, I will close it for now. Would be great if you amend the documentation with recommendations on infrastructure resources.

**Comment by SJAtreya-TCIN** [comment]
BTW - Great work guys. This is an excellent contribution to the community.

**Comment by Windy810** [comment]
Hello!
I am trying to use one A100 with 80GB RAM (about 60GB is free), but I am still facing the OOM problem. Do u know how can I solve this problem? I tried to use the offload command.
` --offload_diffusion_transformer \
    --offload_text_encoder_model \
    --offload_guardrail_models`

**Comment by fsergiy** [comment]
HI @Windy810 - could you please switch to Cosmos-Transfer2.5 instead?

**Comment by Windy810** [comment]
Ok, thank you for your reply. I'll try to use the new version. 

> HI [@Windy810](https://github.com/Windy810) - could you please switch to Cosmos-Transfer2.5 instead?

**Comment by SJAtreya-TCIN** [comment]
I did try with one H100 GPU (AWS p5.4xlarge) and it works like a charm, both cosmos-transfer1 and 2.5. 

2.5 is much faster and easy to setup IMHO. Haven't tried it for my use-cases, but it definitely looks very promising.
